// Fourier Bench: signals whose answer is already known.
//
// A tool that measures something should be pointed at something whose value is
// not in doubt before it is pointed at anything else. Feed this bench a square
// wave and it should report partials at f, 3f, 5f, 7f and nothing between
// them, with amplitudes 4/πn — a result Fourier published in 1822 and which
// does not depend on this or any other implementation being right. Where a
// signal's partials have a closed form, it is given here as `truth`, and the
// page prints it in the column beside the measurement rather than asking
// anyone to take the measurement on trust.
//
// Every generated signal is faded in and out over 20 ms. Not cosmetics: a tone
// that begins mid-cycle is a step discontinuity, a step is broadband, and the
// first analysis frame would then be measuring a click rather than the tone —
// which is a true fact about the signal and a misleading one about the tool.
// Recorded sound starts from silence and does not have the problem.

(function (root) {
  'use strict';

  const TAU = Math.PI * 2;
  const FADE = 0.02;

  function shape(x, rate) {
    const n = Math.min(Math.floor(FADE * rate), x.length >> 1);
    for (let i = 0; i < n; i++) {
      const g = 0.5 - 0.5 * Math.cos((Math.PI * i) / n);
      x[i] *= g;
      x[x.length - 1 - i] *= g;
    }
    return x;
  }

  function build(rate, seconds, fn) {
    const n = Math.round(rate * seconds);
    const x = new Float64Array(n);
    for (let i = 0; i < n; i++) x[i] = fn(i / rate, i);
    // Leave a little headroom rather than normalising to full scale: a partial
    // list resynthesised can overshoot the original slightly, and a signal
    // already at 1.0 would clip on the way out and make the residual look like
    // distortion the analysis had invented.
    let peak = 0;
    for (let i = 0; i < n; i++) peak = Math.max(peak, Math.abs(x[i]));
    if (peak > 0) for (let i = 0; i < n; i++) x[i] = (x[i] / peak) * 0.8;
    return shape(x, rate);
  }

  // A partial list, in the same shape the analysis produces, so the page can
  // set the two side by side without either knowing about the other.
  function series(f0, amps) {
    return amps
      .map((a, i) => ({ n: i + 1, hz: f0 * (i + 1), amp: Math.abs(a) }))
      .filter((p) => p.amp > 1e-6);
  }

  // ── Band-limiting ─────────────────────────────────────────────────────────
  //
  // The classic waveforms are built by adding their harmonics up to Nyquist,
  // not by the obvious one-liners — not Math.sign(sin) for a square, not
  // 2·(t·f mod 1)−1 for a sawtooth. Those have corners, a corner has harmonics
  // for ever, and every harmonic above half the sampling rate comes back down
  // as a partial at a frequency that is not a multiple of anything. On a 220 Hz
  // square at 44.1 kHz that puts a spurious peak at 324.87 Hz, some 51 dB down
  // and entirely real in the file.
  //
  // Which would make this the wrong test signal, because the closed form in the
  // truth column assumes those harmonics are where the series says and not
  // folded back. A signal generated by summing its own partials is the one
  // whose answer is genuinely known — and it is the sampled square wave, in the
  // sense that any other sampled square wave is this one plus aliasing error.
  function additive(rate, sec, f0, amp) {
    const nyq = rate / 2;
    const parts = [];
    for (let n = 1; n * f0 < nyq * 0.999; n++) {
      const a = amp(n);
      if (a) parts.push([n * f0, a]);
    }
    return build(rate, sec, (t) => {
      let v = 0;
      for (let i = 0; i < parts.length; i++) v += parts[i][1] * Math.sin(TAU * parts[i][0] * t);
      return v;
    });
  }

  const SIGNALS = [
    {
      id: 'sine',
      name: 'Sine',
      says: 'One partial and nothing else. Anything the bench reports beyond a single peak is the window, not the sound.',
      make: (rate, sec, hz) => build(rate, sec, (t) => Math.sin(TAU * hz * t)),
      truth: (hz) => series(hz, [1]),
    },
    {
      id: 'square',
      name: 'Square',
      says: 'Odd harmonics at 4/πn, nothing on the even ones. The oldest worked example there is.',
      make: (rate, sec, hz) =>
        additive(rate, sec, hz, (n) => (n % 2 ? 4 / (Math.PI * n) : 0)),
      truth: (hz) => series(hz, Array.from({ length: 32 }, (_, i) =>
        (i + 1) % 2 ? 4 / (Math.PI * (i + 1)) : 0)),
    },
    {
      id: 'saw',
      name: 'Sawtooth',
      says: 'Every harmonic, at 2/πn. The same falloff as a square with the gaps filled in.',
      make: (rate, sec, hz) =>
        additive(rate, sec, hz, (n) => (n % 2 ? 1 : -1) * (2 / (Math.PI * n))),
      truth: (hz) => series(hz, Array.from({ length: 32 }, (_, i) => 2 / (Math.PI * (i + 1)))),
    },
    {
      id: 'triangle',
      name: 'Triangle',
      says: 'Odd harmonics at 8/π²n², falling four times faster than a square. Why it sounds closer to a sine.',
      make: (rate, sec, hz) =>
        additive(rate, sec, hz, (n) =>
          n % 2 ? ((n - 1) / 2 % 2 ? -1 : 1) * (8 / (Math.PI * Math.PI * n * n)) : 0),
      truth: (hz) => series(hz, Array.from({ length: 32 }, (_, i) =>
        (i + 1) % 2 ? 8 / (Math.PI * Math.PI * (i + 1) * (i + 1)) : 0)),
    },
    {
      id: 'pair',
      name: 'Two close tones',
      says: 'Two sines a whole tone apart, then 3 Hz apart. The second pair needs a window long enough to separate them, and shows what happens when it is not.',
      make: (rate, sec, hz) =>
        build(rate, sec, (t) =>
          t < sec / 2
            ? Math.sin(TAU * hz * t) + Math.sin(TAU * hz * 1.1225 * t)
            : Math.sin(TAU * hz * t) + Math.sin(TAU * (hz + 3) * t)),
      truth: null,
    },
    {
      id: 'chirp',
      name: 'Chirp',
      says: 'A sweep from the fundamental to sixteen times it. A diagonal line, and the width of that line is the window.',
      make: (rate, sec, hz) => {
        const k = (hz * 15) / sec;
        return build(rate, sec, (t) => Math.sin(TAU * (hz * t + (k * t * t) / 2)));
      },
      truth: null,
    },
    {
      id: 'pluck',
      name: 'Plucked string',
      says: 'Harmonics that decay faster the higher they are, over a stiff string. The bench should recover both the pitch and the stiffness.',
      make: (rate, sec, hz) => {
        const B = 3.5e-4;
        return build(rate, sec, (t) => {
          let v = 0;
          for (let n = 1; n <= 20; n++) {
            const f = n * hz * Math.sqrt(1 + B * n * n);
            if (f > 20000) break;
            v += (1 / n) * Math.exp(-t * (1.5 + n * 0.9)) * Math.sin(TAU * f * t + n);
          }
          return v;
        });
      },
      truth: null,
    },
    {
      id: 'bell',
      name: 'Bell',
      says: 'Partials at 0.5, 1, 1.2, 1.5, 2, 2.5 and 3 times the strike note — a real bell\'s ratios, and not a harmonic series. Most of these get no harmonic number, which is the correct answer.',
      make: (rate, sec, hz) => {
        const ratios = [0.5, 1, 1.2, 1.5, 2, 2.5, 3, 4];
        const decay = [0.6, 1.1, 1.6, 2.2, 2.8, 3.6, 4.4, 6];
        return build(rate, sec, (t) => {
          let v = 0;
          for (let i = 0; i < ratios.length; i++) {
            v += (1 / (1 + i * 0.5)) * Math.exp(-t * decay[i]) *
                 Math.sin(TAU * hz * ratios[i] * t + i * 1.7);
          }
          return v;
        });
      },
      truth: null,
    },
    {
      id: 'vibrato',
      name: 'Vibrato',
      says: 'One partial, wobbling a semitone at 5 Hz. A single frame cannot see a wobble; the track across frames can.',
      make: (rate, sec, hz) =>
        build(rate, sec, (t) =>
          Math.sin(TAU * hz * (t + (0.03 / (TAU * 5)) * Math.sin(TAU * 5 * t)))),
      truth: null,
    },
    {
      id: 'noise',
      name: 'White noise',
      says: 'No partials at all. Every peak the bench finds here is a peak in noise, which is what the floor control is for.',
      make: (rate, sec) => {
        // A fixed seed, so the same noise comes back and two runs can be
        // compared. Math.random would make every result unrepeatable.
        let z = 0x2f6e2b1;
        return build(rate, sec, () => {
          z ^= z << 13; z >>>= 0;
          z ^= z >> 17;
          z ^= z << 5; z >>>= 0;
          return (z / 0xffffffff) * 2 - 1;
        });
      },
      truth: null,
    },
  ];

  function byId(id) {
    return SIGNALS.filter((s) => s.id === id)[0] || SIGNALS[0];
  }

  // The generator normalises to 0.8 peak, so a closed-form amplitude has to be
  // put on the same footing before it can be compared with a measurement. The
  // measured fundamental is what puts it there: anchoring on it compares the
  // shape of the series, which is the part Fourier settled, rather than the
  // level this particular file happens to sit at, which is arbitrary.
  function truthFor(sig, hz, measuredFundamental) {
    if (!sig.truth) return null;
    const t = sig.truth(hz);
    if (!t.length) return null;
    // Anchor on the fundamental actually measured, so the column compares the
    // shape of the series rather than the level the file happens to sit at.
    const k = measuredFundamental > 0 ? measuredFundamental / t[0].amp : 1;
    return t.map((p) => ({ n: p.n, hz: p.hz, amp: p.amp * k }));
  }

  root.Signals = {
    list: SIGNALS,
    byId: byId,
    truthFor: truthFor,
  };
})(typeof self !== 'undefined' ? self : globalThis);
